// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArgInitParameters struct {

	// An expression to be used as default value if the parameter is not specified.
	// An expression to be used as default value if the parameter is not specified.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Can be one of IN, INOUT, OUT, or VARIADIC. Default is IN.
	// The argument mode. One of: IN, OUT, INOUT, or VARIADIC
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The name of the function.
	// The argument name. The name may be required for some languages or depending on the argument mode.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The type of the argument.
	// The argument type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ArgObservation struct {

	// An expression to be used as default value if the parameter is not specified.
	// An expression to be used as default value if the parameter is not specified.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Can be one of IN, INOUT, OUT, or VARIADIC. Default is IN.
	// The argument mode. One of: IN, OUT, INOUT, or VARIADIC
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The name of the function.
	// The argument name. The name may be required for some languages or depending on the argument mode.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The type of the argument.
	// The argument type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ArgParameters struct {

	// An expression to be used as default value if the parameter is not specified.
	// An expression to be used as default value if the parameter is not specified.
	// +kubebuilder:validation:Optional
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Can be one of IN, INOUT, OUT, or VARIADIC. Default is IN.
	// The argument mode. One of: IN, OUT, INOUT, or VARIADIC
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The name of the function.
	// The argument name. The name may be required for some languages or depending on the argument mode.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The type of the argument.
	// The argument type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type FunctionInitParameters struct {

	// List of arguments for the function.
	// Function argument definitions.
	Arg []ArgInitParameters `json:"arg,omitempty" tf:"arg,omitempty"`

	// Function body.
	// This should be the body content within the AS $$ and the final $$. It will also accept the AS $$ and $$ if added.
	// Body of the function.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// The database where the function is located.
	// If not specified, the function is created in the current database.
	// The database where the function is located. If not specified, the provider default database is used.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// True to automatically drop objects that depend on the function (such as
	// operators or triggers), and in turn all objects that depend on those objects. Default is false.
	// Automatically drop objects that depend on the function (such as operators or triggers), and in turn all objects that depend on those objects.
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	// The function programming language. Can be one of internal, sql, c, plpgsql. Default is plpgsql.
	// Language of theof the function. One of: internal, sql, c, plpgsql
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// The name of the function.
	// Name of the function.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates if the function is parallel safe. Can be one of UNSAFE, RESTRICTED, or SAFE. Default is UNSAFE.
	// If the function can be executed in parallel for a single query execution. One of: UNSAFE, RESTRICTED, SAFE
	Parallel *string `json:"parallel,omitempty" tf:"parallel,omitempty"`

	// Type that the function returns. It can be computed from the OUT arguments. Default is void.
	// Function return type. If not specified, it will be calculated based on the output arguments
	Returns *string `json:"returns,omitempty" tf:"returns,omitempty"`

	// The schema where the function is located.
	// If not specified, the function is created in the current schema.
	// Schema where the function is located. If not specified, the provider default schema is used.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// If the function should execute with the permissions of the owner, rather than the permissions of the caller. Default is false.
	// If the function should execute with the permissions of the function owner instead of the permissions of the caller.
	SecurityDefiner *bool `json:"securityDefiner,omitempty" tf:"security_definer,omitempty"`

	// If the function should always return NULL when any of the inputs is NULL. Default is false.
	// If the function should always return NULL if any of it's inputs is NULL.
	Strict *bool `json:"strict,omitempty" tf:"strict,omitempty"`

	// Defines the volatility of the function. Can be one of VOLATILE, STABLE, or IMMUTABLE. Default is VOLATILE.
	// Volatility of the function. One of: VOLATILE, STABLE, IMMUTABLE.
	Volatility *string `json:"volatility,omitempty" tf:"volatility,omitempty"`
}

type FunctionObservation struct {

	// List of arguments for the function.
	// Function argument definitions.
	Arg []ArgObservation `json:"arg,omitempty" tf:"arg,omitempty"`

	// Function body.
	// This should be the body content within the AS $$ and the final $$. It will also accept the AS $$ and $$ if added.
	// Body of the function.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// The database where the function is located.
	// If not specified, the function is created in the current database.
	// The database where the function is located. If not specified, the provider default database is used.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// True to automatically drop objects that depend on the function (such as
	// operators or triggers), and in turn all objects that depend on those objects. Default is false.
	// Automatically drop objects that depend on the function (such as operators or triggers), and in turn all objects that depend on those objects.
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The function programming language. Can be one of internal, sql, c, plpgsql. Default is plpgsql.
	// Language of theof the function. One of: internal, sql, c, plpgsql
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// The name of the function.
	// Name of the function.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates if the function is parallel safe. Can be one of UNSAFE, RESTRICTED, or SAFE. Default is UNSAFE.
	// If the function can be executed in parallel for a single query execution. One of: UNSAFE, RESTRICTED, SAFE
	Parallel *string `json:"parallel,omitempty" tf:"parallel,omitempty"`

	// Type that the function returns. It can be computed from the OUT arguments. Default is void.
	// Function return type. If not specified, it will be calculated based on the output arguments
	Returns *string `json:"returns,omitempty" tf:"returns,omitempty"`

	// The schema where the function is located.
	// If not specified, the function is created in the current schema.
	// Schema where the function is located. If not specified, the provider default schema is used.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// If the function should execute with the permissions of the owner, rather than the permissions of the caller. Default is false.
	// If the function should execute with the permissions of the function owner instead of the permissions of the caller.
	SecurityDefiner *bool `json:"securityDefiner,omitempty" tf:"security_definer,omitempty"`

	// If the function should always return NULL when any of the inputs is NULL. Default is false.
	// If the function should always return NULL if any of it's inputs is NULL.
	Strict *bool `json:"strict,omitempty" tf:"strict,omitempty"`

	// Defines the volatility of the function. Can be one of VOLATILE, STABLE, or IMMUTABLE. Default is VOLATILE.
	// Volatility of the function. One of: VOLATILE, STABLE, IMMUTABLE.
	Volatility *string `json:"volatility,omitempty" tf:"volatility,omitempty"`
}

type FunctionParameters struct {

	// List of arguments for the function.
	// Function argument definitions.
	// +kubebuilder:validation:Optional
	Arg []ArgParameters `json:"arg,omitempty" tf:"arg,omitempty"`

	// Function body.
	// This should be the body content within the AS $$ and the final $$. It will also accept the AS $$ and $$ if added.
	// Body of the function.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// The database where the function is located.
	// If not specified, the function is created in the current database.
	// The database where the function is located. If not specified, the provider default database is used.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// True to automatically drop objects that depend on the function (such as
	// operators or triggers), and in turn all objects that depend on those objects. Default is false.
	// Automatically drop objects that depend on the function (such as operators or triggers), and in turn all objects that depend on those objects.
	// +kubebuilder:validation:Optional
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	// The function programming language. Can be one of internal, sql, c, plpgsql. Default is plpgsql.
	// Language of theof the function. One of: internal, sql, c, plpgsql
	// +kubebuilder:validation:Optional
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// The name of the function.
	// Name of the function.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates if the function is parallel safe. Can be one of UNSAFE, RESTRICTED, or SAFE. Default is UNSAFE.
	// If the function can be executed in parallel for a single query execution. One of: UNSAFE, RESTRICTED, SAFE
	// +kubebuilder:validation:Optional
	Parallel *string `json:"parallel,omitempty" tf:"parallel,omitempty"`

	// Type that the function returns. It can be computed from the OUT arguments. Default is void.
	// Function return type. If not specified, it will be calculated based on the output arguments
	// +kubebuilder:validation:Optional
	Returns *string `json:"returns,omitempty" tf:"returns,omitempty"`

	// The schema where the function is located.
	// If not specified, the function is created in the current schema.
	// Schema where the function is located. If not specified, the provider default schema is used.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// If the function should execute with the permissions of the owner, rather than the permissions of the caller. Default is false.
	// If the function should execute with the permissions of the function owner instead of the permissions of the caller.
	// +kubebuilder:validation:Optional
	SecurityDefiner *bool `json:"securityDefiner,omitempty" tf:"security_definer,omitempty"`

	// If the function should always return NULL when any of the inputs is NULL. Default is false.
	// If the function should always return NULL if any of it's inputs is NULL.
	// +kubebuilder:validation:Optional
	Strict *bool `json:"strict,omitempty" tf:"strict,omitempty"`

	// Defines the volatility of the function. Can be one of VOLATILE, STABLE, or IMMUTABLE. Default is VOLATILE.
	// Volatility of the function. One of: VOLATILE, STABLE, IMMUTABLE.
	// +kubebuilder:validation:Optional
	Volatility *string `json:"volatility,omitempty" tf:"volatility,omitempty"`
}

// FunctionSpec defines the desired state of Function
type FunctionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FunctionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FunctionInitParameters `json:"initProvider,omitempty"`
}

// FunctionStatus defines the observed state of Function.
type FunctionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FunctionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Function is the Schema for the Functions API. Creates and manages a function on a PostgreSQL server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,postgresql}
type Function struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FunctionSpec   `json:"spec"`
	Status FunctionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FunctionList contains a list of Functions
type FunctionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Function `json:"items"`
}

// Repository type metadata.
var (
	Function_Kind             = "Function"
	Function_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Function_Kind}.String()
	Function_KindAPIVersion   = Function_Kind + "." + CRDGroupVersion.String()
	Function_GroupVersionKind = CRDGroupVersion.WithKind(Function_Kind)
)

func init() {
	SchemeBuilder.Register(&Function{}, &FunctionList{})
}
