// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Extension) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Function) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Grant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Publication) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Schema) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Server) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subscription) Hub() {}
