// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServerInitParameters struct {

	// When true, will drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects . (Default: false)
	// Automatically drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects. Drop RESTRICT is the default
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	// The name of the foreign-data wrapper that manages the server.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// The name of the foreign-data wrapper that manages the server
	FdwName *string `json:"fdwName,omitempty" tf:"fdw_name,omitempty"`

	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper.
	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper
	// +mapType=granular
	Options map[string]*string `json:"options,omitempty" tf:"options,omitempty"`

	// The name of the foreign server to be created.
	// The name of the foreign server to be created
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// By default, the user who defines the server becomes its owner. Set this value to configure the new owner of the foreign server.
	// The user name of the new owner of the foreign server
	ServerOwner *string `json:"serverOwner,omitempty" tf:"server_owner,omitempty"`

	// Optional server type, potentially useful to foreign-data wrappers.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// Optional server type, potentially useful to foreign-data wrappers
	ServerType *string `json:"serverType,omitempty" tf:"server_type,omitempty"`

	// Optional server version, potentially useful to foreign-data wrappers.
	// Optional server version, potentially useful to foreign-data wrappers.
	ServerVersion *string `json:"serverVersion,omitempty" tf:"server_version,omitempty"`
}

type ServerObservation struct {

	// When true, will drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects . (Default: false)
	// Automatically drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects. Drop RESTRICT is the default
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	// The name of the foreign-data wrapper that manages the server.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// The name of the foreign-data wrapper that manages the server
	FdwName *string `json:"fdwName,omitempty" tf:"fdw_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper.
	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper
	// +mapType=granular
	Options map[string]*string `json:"options,omitempty" tf:"options,omitempty"`

	// The name of the foreign server to be created.
	// The name of the foreign server to be created
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// By default, the user who defines the server becomes its owner. Set this value to configure the new owner of the foreign server.
	// The user name of the new owner of the foreign server
	ServerOwner *string `json:"serverOwner,omitempty" tf:"server_owner,omitempty"`

	// Optional server type, potentially useful to foreign-data wrappers.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// Optional server type, potentially useful to foreign-data wrappers
	ServerType *string `json:"serverType,omitempty" tf:"server_type,omitempty"`

	// Optional server version, potentially useful to foreign-data wrappers.
	// Optional server version, potentially useful to foreign-data wrappers.
	ServerVersion *string `json:"serverVersion,omitempty" tf:"server_version,omitempty"`
}

type ServerParameters struct {

	// When true, will drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects . (Default: false)
	// Automatically drop objects that depend on the server (such as user mappings), and in turn all objects that depend on those objects. Drop RESTRICT is the default
	// +kubebuilder:validation:Optional
	DropCascade *bool `json:"dropCascade,omitempty" tf:"drop_cascade,omitempty"`

	// The name of the foreign-data wrapper that manages the server.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// The name of the foreign-data wrapper that manages the server
	// +kubebuilder:validation:Optional
	FdwName *string `json:"fdwName,omitempty" tf:"fdw_name,omitempty"`

	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper.
	// This clause specifies the options for the server. The options typically define the connection details of the server, but the actual names and values are dependent on the server's foreign-data wrapper
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Options map[string]*string `json:"options,omitempty" tf:"options,omitempty"`

	// The name of the foreign server to be created.
	// The name of the foreign server to be created
	// +kubebuilder:validation:Optional
	ServerName *string `json:"serverName,omitempty" tf:"server_name,omitempty"`

	// By default, the user who defines the server becomes its owner. Set this value to configure the new owner of the foreign server.
	// The user name of the new owner of the foreign server
	// +kubebuilder:validation:Optional
	ServerOwner *string `json:"serverOwner,omitempty" tf:"server_owner,omitempty"`

	// Optional server type, potentially useful to foreign-data wrappers.
	// Changing this value
	// will force the creation of a new resource as this value can only be set
	// when the foreign server is created.
	// Optional server type, potentially useful to foreign-data wrappers
	// +kubebuilder:validation:Optional
	ServerType *string `json:"serverType,omitempty" tf:"server_type,omitempty"`

	// Optional server version, potentially useful to foreign-data wrappers.
	// Optional server version, potentially useful to foreign-data wrappers.
	// +kubebuilder:validation:Optional
	ServerVersion *string `json:"serverVersion,omitempty" tf:"server_version,omitempty"`
}

// ServerSpec defines the desired state of Server
type ServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerInitParameters `json:"initProvider,omitempty"`
}

// ServerStatus defines the observed state of Server.
type ServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Server is the Schema for the Servers API. Creates and manages a foreign server on a PostgreSQL server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,postgresql}
type Server struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fdwName) || (has(self.initProvider) && has(self.initProvider.fdwName))",message="spec.forProvider.fdwName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverName) || (has(self.initProvider) && has(self.initProvider.serverName))",message="spec.forProvider.serverName is a required parameter"
	Spec   ServerSpec   `json:"spec"`
	Status ServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerList contains a list of Servers
type ServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Server `json:"items"`
}

// Repository type metadata.
var (
	Server_Kind             = "Server"
	Server_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Server_Kind}.String()
	Server_KindAPIVersion   = Server_Kind + "." + CRDGroupVersion.String()
	Server_GroupVersionKind = CRDGroupVersion.WithKind(Server_Kind)
)

func init() {
	SchemeBuilder.Register(&Server{}, &ServerList{})
}
