// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SubscriptionInitParameters struct {

	// Specifies whether the command should create the replication slot on the publisher
	CreateSlot *bool `json:"createSlot,omitempty" tf:"create_slot,omitempty"`

	// Sets the database to add the subscription for
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The name of the subscription
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Names of the publications on the publisher to subscribe to
	// +listType=set
	Publications []*string `json:"publications,omitempty" tf:"publications,omitempty"`

	// Name of the replication slot to use. The default behavior is to use the name of the subscription for the slot name
	SlotName *string `json:"slotName,omitempty" tf:"slot_name,omitempty"`
}

type SubscriptionObservation struct {

	// Specifies whether the command should create the replication slot on the publisher
	CreateSlot *bool `json:"createSlot,omitempty" tf:"create_slot,omitempty"`

	// Sets the database to add the subscription for
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the subscription
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Names of the publications on the publisher to subscribe to
	// +listType=set
	Publications []*string `json:"publications,omitempty" tf:"publications,omitempty"`

	// Name of the replication slot to use. The default behavior is to use the name of the subscription for the slot name
	SlotName *string `json:"slotName,omitempty" tf:"slot_name,omitempty"`
}

type SubscriptionParameters struct {

	// The connection string to the publisher. It should follow the keyword/value format (https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)
	// +kubebuilder:validation:Optional
	ConninfoSecretRef v1.SecretKeySelector `json:"conninfoSecretRef" tf:"-"`

	// Specifies whether the command should create the replication slot on the publisher
	// +kubebuilder:validation:Optional
	CreateSlot *bool `json:"createSlot,omitempty" tf:"create_slot,omitempty"`

	// Sets the database to add the subscription for
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The name of the subscription
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Names of the publications on the publisher to subscribe to
	// +kubebuilder:validation:Optional
	// +listType=set
	Publications []*string `json:"publications,omitempty" tf:"publications,omitempty"`

	// Name of the replication slot to use. The default behavior is to use the name of the subscription for the slot name
	// +kubebuilder:validation:Optional
	SlotName *string `json:"slotName,omitempty" tf:"slot_name,omitempty"`
}

// SubscriptionSpec defines the desired state of Subscription
type SubscriptionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SubscriptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubscriptionInitParameters `json:"initProvider,omitempty"`
}

// SubscriptionStatus defines the observed state of Subscription.
type SubscriptionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubscriptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subscription is the Schema for the Subscriptions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,postgresql}
type Subscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.conninfoSecretRef)",message="spec.forProvider.conninfoSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publications) || (has(self.initProvider) && has(self.initProvider.publications))",message="spec.forProvider.publications is a required parameter"
	Spec   SubscriptionSpec   `json:"spec"`
	Status SubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubscriptionList contains a list of Subscriptions
type SubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subscription `json:"items"`
}

// Repository type metadata.
var (
	Subscription_Kind             = "Subscription"
	Subscription_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subscription_Kind}.String()
	Subscription_KindAPIVersion   = Subscription_Kind + "." + CRDGroupVersion.String()
	Subscription_GroupVersionKind = CRDGroupVersion.WithKind(Subscription_Kind)
)

func init() {
	SchemeBuilder.Register(&Subscription{}, &SubscriptionList{})
}
