// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/tagesjump/provider-postgresql/apis/default/v1alpha1"
	v1alpha1grant "github.com/tagesjump/provider-postgresql/apis/grant/v1alpha1"
	v1alpha1physical "github.com/tagesjump/provider-postgresql/apis/physical/v1alpha1"
	v1alpha1postgresql "github.com/tagesjump/provider-postgresql/apis/postgresql/v1alpha1"
	v1alpha1replication "github.com/tagesjump/provider-postgresql/apis/replication/v1alpha1"
	v1alpha1user "github.com/tagesjump/provider-postgresql/apis/user/v1alpha1"
	v1alpha1apis "github.com/tagesjump/provider-postgresql/apis/v1alpha1"
	v1beta1 "github.com/tagesjump/provider-postgresql/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1grant.SchemeBuilder.AddToScheme,
		v1alpha1physical.SchemeBuilder.AddToScheme,
		v1alpha1postgresql.SchemeBuilder.AddToScheme,
		v1alpha1replication.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
